# -*- coding: utf-8 -*-
"""creador de imagenes aleatorias de inteligencia artificial de a drive

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XlO4pzqGIh8Y15RxU2246DaOEAS7wU4x
"""

client = InferenceClient("stabilityai/stable-diffusion-xl-base-1.0", token=HF_TOKEN)

!pip install huggingface_hub

import requests
from datetime import datetime
from PIL import Image
import io
import matplotlib.pyplot as plt

import os

# 🔑 Tu token de Hugging Face (lo leerá desde un Secret en GitHub)
HF_TOKEN = os.getenv("HF_TOKEN")


# Modelo correcto que sí existe
API_URL = "https://api-inference.huggingface.co/models/stabilityai/stable-diffusion-xl-base-1.0"

headers = {"Authorization": f"Bearer {HF_TOKEN}"}

def query(payload):
    response = requests.post(API_URL, headers=headers, json=payload)
    if response.status_code != 200:
        raise Exception(f"Error {response.status_code}: {response.text}")
    return response.content

# Prompt aleatorio
import random
lugares = ["un bosque encantado", "una ciudad futurista", "un desierto infinito", "un planeta alienígena", "un océano profundo", "una metrópolis antigua", "una montaña de cristal"]
estilos = ["en estilo cyberpunk", "en estilo pintura al óleo", "en estilo anime", "con arte digital hiperrealista", "como ilustración de cómic", "en estilo surrealista"]
detalles = ["con dragones volando", "con luces de neón", "con criaturas mágicas", "durante una tormenta eléctrica", "al amanecer", "bajo una lluvia de estrellas", "en un ambiente post-apocalíptico"]

prompt = f"{random.choice(lugares)} {random.choice(estilos)} {random.choice(detalles)}"
print("🎨 Prompt generado:", prompt)


# Generar imagen
image_bytes = query({"inputs": prompt})

# Guardar y mostrar
filename = f"imagen_{datetime.now().strftime('%Y%m%d_%H%M%S')}.png"
with open(filename, "wb") as f:
    f.write(image_bytes)

image = Image.open(io.BytesIO(image_bytes))
plt.imshow(image)
plt.axis("off")
plt.show()

print("✅ Imagen generada y guardada como:", filename)

from google.colab import drive

# Conectar Colab con tu Google Drive
drive.mount('/content/drive')

import os, shutil

# Carpeta en tu Google Drive
save_path = "/content/drive/MyDrive/imagenes_instagram"
os.makedirs(save_path, exist_ok=True)

# Mover la imagen generada a tu carpeta en Drive
shutil.move(filename, f"{save_path}/{filename}")

print("✅ Imagen guardada en Google Drive en:", save_path)