name: Generar imagen diaria

on:
  schedule:
    - cron: "0 12 * * *"   # ⏰ Ejecuta todos los días a las 12:00 UTC
  workflow_dispatch:       # Permite ejecutarlo manualmente también

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          pip install requests pillow

      - name: Ejecutar script
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python creador_de_imagenes.py
